endlessm/gtk

- gtk/gtkicontheme.c
In order to provide a constant mtime between OS build and deploy time,
while also maintaining a hardlink content-addressed model independent of
timestamps, ostree sets all mtimes to 0.
The icon cache code currently ignores directories with mtime 0, assuming
they don't exist.
Track directory existence in a more precise way.
https://bugzilla.gnome.org/show_bug.cgi?id=745052
https://github.com/endlessm/eos-shell/issues/4601
> icontheme: allow directories with mtime 0

- gtk/gtkwindow.c
To calculate the shadow width, we look at the value of priv->fullscreen
and priv->maximized.
Those fields will have the actual value only after GTK receives back a
window state event though, so they will be wrong in _realize(). Look at
priv->fullscreen_initially and priv->maximize_initially too, to avoid
the size changing right after realize, which would make the window
flicker if maximized at startup.
[endlessm/eos-shell#4943]
> window: fix initial shadow width for maximized/fullscreen windows

- gtk/gtkframe.c
Lots of applications often use GtkFrame as a giant toplevel container,
and that means that they get size allocated often. When frames get size
allocated, they invalidate their entire widget tree, even if they
haven't changed size or anything like that happens at all. This is
because the shadow / label needs to be redrawn if the child changes
size. We can optimize this out and only mark ourselves for a redraw if
the child has actually changed its size.
[endlessm/eos-shell#5259]
> gtkframe: Don't queue a redraw on the entire widget every size allocate

- gtk/gtkwindow.c
Some applications are always on top, or don't have different styles for
backdrop. In that case, it's desirable not to pay the performance
penalty of backdrop style switching.
Add an environment variable as a low-tech way for applications to ask
for that behavior.
[endlessm/eos-shell#5813]
> gtkwindow: add an environment variable to disable backdrop styling

- debian/control
- debian/control.in
Apparently whatever pulling the xmlcatalog tool on debian is not working
for us
[endlessm/eos-sdk#3590]
> Add back libxml2-utils dependency

- gdk/x11/gdkdisplay-x11.c
- gtk/gtkapplication.c
- gtk/gtkwindow.c
Presently, Gtk will only send a startup notification completion message
for the first window that is shown.  This is not good for the case of
GtkApplication, where we are expected to participate in
startup-notification for all windows.
We have avoided this problem by manually emitting the startup complete
message from after_emit in GtkApplication.
Unfortunately, this causes problems for windows that are shown with a
delay.  It is also a dirty hack.
The reason for the original behaviour is simple: there is a static
boolean in gtkwindow.c which controls it.  We remove this.
Instead, clear the startup notification ID stored in GDK when sending
the completion message.  GtkApplication will re-set this the next time
an event comes in which needs startup-notification handling.  In the …
> Tweak startup-notification after the first window

- gtk/theme/Adwaita/_common.scss
- gtk/theme/Adwaita/gtk-contained-dark.css
- gtk/theme/Adwaita/gtk-contained.css
If the theme has rounded corners for fullscreen, we don't tell the
window manager that we are now fully opaque, which then makes things
less efficient than they should be.
https://bugzilla.gnome.org//show_bug.cgi?id=761571
[endlessm/eos-shell#6289]
> Adwaita: No rounded corners for fullscreen

- debian/libgtk-3-0.symbols
When we update to the next stable release, these will be symbols
for 3.20, not 3.18
> New symbols for unstable api we are bringing in

- debian/libgtk-3-0.symbols
We can't support the wayland backend on arm because of our old
kernel version there.
https://phabricator.endlessm.com/T11000
> wayland symbols only for intel

- gtk/gtkicontheme.c
Make sure to always look in EndlessOS theme in case GTK+ can't find
the actual theme currently selected via GSettings, which can happen
for instance when in a ENOSPC situation (i.e. XSettings's property
'Net/IconThemeName' would not be set to the value set in the GSettings
schema for org.gnome.desktop.interface.icon-theme from the xsettings
plugin in gnome-settings-manager, due to broken connectino via dconf).
https://phabricator.endlessm.com/T11550
> Use EndlessOS icon theme as first fallback after checking he current theme

- debian/libgtk-3-0.symbols
Add the GtkScrolledWindow:max-content-width and :max-content-height
symbols to the debian symbol file.
https://phabricator.endlessm.com/T12169
> debian: add new symbols

- gtk/gtkiconhelper.c
After checking for rendered_surface, the call to gtk_css_node_get_style
can invalidate the style and result in rendered_surface being set to
NULL. This was result in some icon views appearing blank on
Endless OS on armv7hl, and this error:
Gtk-CRITICAL **: gtk_css_style_render_icon_surface: assertion 'surface != NULL' failed
Call gtk_css_node_get_style earlier to ensure we always pass a valid
surface to gtk_css_style_render_icon_surface.
https://bugzilla.gnome.org/show_bug.cgi?id=765649
https://phabricator.endlessm.com/T13524
> _gtk_icon_helper_draw: get style earlier

- gtk/gtklevelbar.c
GtkLevelBar supports adding custom offsets as style classes, and they
are applied whenever the :value property matches. The current code,
however, only updates any CSS nodes when an offset is found, causing
it to not update when a discrete value changes but no custom offset
is added.
Fix that by always updating the CSS nodes.
https://phabricator.endlessm.com/T13578
> levelbar: update css nodes even when no offset value is found

- autogen.sh
- testsuite/reftests/Makefile.am
This does the same thing as the corresponding commit on the Debian
branch: skips reftests that are known to fail on the autobuilder.
https://phabricator.endlessm.com/T14197
> TMP: Remove broken reftests

- gtk/gtkapplication-dbus.c
The GNOME session manager, the Xfce session manager, and the Inhibit
portal are all not needed for normal operation of GTK, and it's expected
that they're not present on some systems. So we should not log warnings
if they are not found.
https://bugzilla.gnome.org/show_bug.cgi?id=774784
https://phabricator.endlessm.com/T14586
> GtkApplication: Lack of optional components shouldn't warn

- gdk/x11/gdkdisplay-x11.h
- gdk/x11/gdkglcontext-x11-eglx.c
Use EGL_KHR_image_pixmap extension to implement texture_from_surface() method.
This avoid doing a copy to render GL content to GTK+
https://phabricator.endlessm.com/T15893
> GdkX11GLContext: x11-eglx, implemented texture_from_surface()

- gtk/gtkcssnode.c
~Company ╡ so TL;DR: we put the static style in the cache, but then
⤷ ╡ compute a child style from the animated style in the cache
⤷ ╡ and we put the child style also in the cache (because
⤷ ╡ it's not animated)
⤷ ╡ then we run the animation, but reuse the cache every time
⤷ ╡ for both child and parent
⤷ ╡ so after the animation is done, we end up with a cache that
⤷ ╡ has the correct static style for the parent but an
⤷ ╡ incorrect static style for the child
⤷ ╡ because that static style was computed from the
⤷ ╡ initial animated style
This fixes https://bugzilla.gnome.org/show_bug.cgi?id=763517
https://phabricator.endlessm.com/T19435
> cssnode: Don't put wrong styles in the style cache

- gtk/theme/Adwaita/_endless.scss
This button is now implemented in gtk3 and can be styled via css.
By default, we want the button background to be transparent
and only appear on hover.
https://phabricator.endlessm.com/T20947
> Chromium header bar: fix user button color for Chrome 64

- gtk/a11y/gtklabelaccessible.c
Since at-spi-atk commit 96621a5e95 fixed PropertyChange notifications
for AccessibleParent, setting the parent will result in a call to
ref_state_set() which assumes that the object is fully initialized.
https://bugzilla.gnome.org/show_bug.cgi?id=774939
https://phabricator.endlessm.com/T21318
> GtkLabelAccessible: Initialize link before setting parent

- gtk/gtkcssimagesurface.c
- gtk/gtkcssimagesurfaceprivate.h
Keep a copy of the scaled image to speed up rendering multiple times
the image at the same size.
https://phabricator.endlessm.com/T21402
> GtkCssImageSurface: add cache for the last drawn size.

- debian/rules
Debian upstream rewrote the packaging to not use cdbs, but our
downstream changes didn't follow suit. Use quilt by passing --with-quilt
to dh, and add our --enable-egl-x11 to the variables built up for
dh_auto_configure.
https://phabricator.endlessm.com/T21675
> Switch rules downstream changes from cdbs to debhelper

- debian/rules
This prevents the udeb package from being built and for some odd reason
allows the ARM build to succeed. But generally this is something we
should be doing since we have no use for udeb packages. Not only are
they only used in debian-installer (which we don't use), but OBS does
even publish them. Furthermore, disabling the udeb roughly cuts the
build time in half since an entirely separate build is done for the
udeb.
I don't think that doing this via DH_OPTIONS is really the recommended
way to do it, but it ensures that all debhelper usage respects the -N
option needed to skip the udeb package.
https://phabricator.endlessm.com/T22286
> Skip building udeb package

- debian/libgtk-3-0.symbols
New symbols:
- gdk_display_get_startup_notification_id
- gdk_wayland_display_get_startup_notification_id
https://phabricator.endlessm.com/T22416
> debian/libgtk-3-0.symbols: Add new symbols from newly added API

- gtk/theme/Adwaita/_endless.scss
- gtk/theme/Adwaita/gtk-contained-dark.css
- gtk/theme/Adwaita/gtk-contained.css
Make more generic the change that was removing the shadows from the titlebar buttons, and also remove some style overrides for the user information that chromium is now showing outside of the toolbar.
> Remove shadows from titlebar buttons and legacy chromium user styles

- gdk/x11/gdkglcontext-x11-eglx.c
Previously, the current EGL context would be set to null when destroying
a GdkGLContext that is not the current context. That is different from
other backends and appears to be a mistake.
https://phabricator.endlessm.com/T26542
> gdkglcontext-x11-eglx: Set current EGL context to null when destroyed

- autogen.sh
- testsuite/reftests/Makefile.am
This does the same thing as the corresponding patch in Debian: skips
reftests that are known to fail on the autobuilder.
(Cherry picked from 35891e6fad5e41c7eb9890fea7eca758b0581bdd, which was
dropped in eos3.5 but now seems to be necessary again for some of the
same tests and some different tests as well; see
https://github.com/endlessm/gtk/pull/88)
https://phabricator.endlessm.com/T27556
> Remove broken reftests

- gtk/gtklistbox.c
It’s possible for code which uses a `GtkListBox` to reuse a single
header row, and move it around between rows. For example, this might
happen if the code has interactive widgets (like buttons) in the row,
and doesn’t want to continually recreate them and reattach signals to
them whenever the row headers change.
Unfortunately, this was broken, as the old header widget was
unconditionally unparented, even if it had just been set as the header
for a different row in the same `GtkListBox`. This left it assigned as
a child widget in the `GtkListBox` (so it was iterated over by
`forall`), but without its parent widget set.
Fix that by only unparenting the header if it hasn’t already been
assigned as the parent of a different row.
Signed-off-by: Philip Withnall <withnall@endlessm.com> …
> gtklistbox: Only unparent header rows if they haven’t been reused
